# ================================================
# Mini-Scan Configuration
# ================================================

# Property values that use the placeholder syntax `${ ... }` are resolved via environment variables. For examples, on a
# POSIX system, the following variable could be defined in `.bashrc`, `.profile`, `.bash_profile`, or via the command
# line:
#
#   export FOO="bar"
#
# which could then be referenced by value:
#
#   some-application-property: ${FOO}
#
# At runtime, the value for `some-application-property` would be `bar`.
#
# The pipe `|` symbol can be used within a placeholder to specify a default value if an environment variable cannot be
# resolved. For examples:
#
#   required-application-property: ${DOES_NOT_EXIST | baz}
#
# At runtime, the value for `required-application-property` would be `baz` if the environment variable `DOES_NOT_EXIST`
# was not set.

# mini-scan configuration.
config:

  # General application configuration.
  application:

    # Sets the name of the application.
    name: mini-scan

    # Sets the application version.
    version: v0.1.0

  # Repository configuration.
  repository:
    
    # OpenSearch repository configuration.
    opensearch:

      # Sets the list of addresses for OpenSearch nodes.
      addresses: ${MS_REPOSITORY_OPENSEARCH_ADDRESSES | http://search-node:9200}

      # The OpenSearch user principal.
      username: ${MS_REPOSITORY_OPENSEARCH_USERNAME | }

      # The password for the OpenSearch user.
      password: ${MS_REPOSITORY_OPENSEARCH_PASSWORD | }

      # Index mapping configuration.
      mapping:

        create: ${MS_REPOSITORY_OPENSEARCH_MAPPING_CREATE | true}

        templatePath: ${MS_REPOSITORY_OPENSEARCH_MAPPING_TEMPLATE_PATH | deploy/migration/opensearch/template}

        indicesPath: ${MS_REPOSITORY_OPENSEARCH_MAPPING_INDICES_PATH | deploy/repository/indices.json}

      retry:

        enable: ${MS_REPOSITORY_OPENSEARCH_RETRY_ENABLE | true}

        status: ${MS_REPOSITORY_OPENSEARCH_RETRY_ON_STATUS | 502,503,504,429}

        max: ${MS_REPOSITORY_OPENSEARCH_RETRY_ON_STATUS | 5}

      # OpenSearch bulk processing configuration.
      bulk:

        # OpenSearch bulk processing flush configuration.
        flush:

          # Sets when to flush a new bulk request based on the size of actions queued for indexing. Default: 5MiB.
          #
          # The value must be an unsigned sequence of decimal numbers followed by a size unit suffix in SI or IEC
          # standard units.
          #
          # Examples:
          #   SI:  512 kb, 5Mb
          #   IEC: 512 KiB, 5MiB
          #
          size: ${MS_REPOSITORY_OPENSEARCH_BULK_FLUSH_SIZE | 1MiB}

          # Duration of time to wait before flushing *any* pending bulk actions. Default: 30 seconds.
          #
          # The value for the flush interval must be an unsigned sequence of decimal numbers followed by a time unit
          # suffix. Valid time units: ns|us|µs|ms|s|m|h
          #
          # Example: 30s
          #
          interval: ${MS_REPOSITORY_OPENSEARCH_BULK_FLUSH_INTERVAL | 30s}

        # Sets whether to enable statistics reporting for bulk operations. Default: true.
        statsEnable: ${MS_REPOSITORY_OPENSEARCH_STATS_ENABLE | true}

        # Sets the maximum number of workers used for concurrently executing bulk actions. Default: number of
        # available CPUs.
        workers: ${MS_REPOSITORY_OPENSEARCH_BULK_WORKERS | }
    
