services:
  # ==============================
  # OpenSearch
  # ==============================
  search-node:
    image: opensearchproject/opensearch:latest
    container_name: search-node
    environment:
      bootstrap.memory_lock: true
      cluster.name: search-cluster
      discovery.seed_hosts: search-node
      discovery.type: single-node
      indices.memory.index_buffer_size: 15%
      network.host: 0.0.0.0
      node.max_local_storage_nodes: 3
      node.name: search-node
      plugins.security.ssl.http.enabled: false
      OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m
      DISABLE_SECURITY_PLUGIN: true
      DISABLE_INSTALL_DEMO_CONFIG: true
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9600:9600
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200 >/dev/null 2>&1" ]
      interval: 10s
      timeout: 5s
      retries: 3
  search-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: search-dashboards
    depends_on:
      search-node:
        condition: service_healthy
    environment:
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
      OPENSEARCH_HOSTS: '["http://search-node:9200"]'
    ports:
      - 127.0.0.1:5601:5601
  # ==============================
  # GCP Pub/Sub
  # ==============================
  pubsub:
    image: google/cloud-sdk:latest
    container_name: pubsub
    environment:
      PUBSUB_EMULATOR_HOST: 'pubsub:8085'
    ports:
      - 127.0.0.1:8085:8085
    command: >
      gcloud beta emulators pubsub start 
      --host-port=0.0.0.0:8085
      --project=test-project
    healthcheck:
      test: ["CMD", "curl", "-f", "http://pubsub:8085"]
      interval: 5s
      timeout: 10s
      retries: 3
  mk-topic:
    image: alpine/httpie
    container_name: mk-topic
    depends_on:
      pubsub:
        condition: service_healthy
    command: PUT http://pubsub:8085/v1/projects/test-project/topics/scan-topic
  mk-subscription:
    image: alpine/httpie
    container_name: mk-subscription
    depends_on:
      mk-topic:
        condition: service_completed_successfully
    command: PUT http://pubsub:8085/v1/projects/test-project/subscriptions/scan-sub topic=projects/test-project/topics/scan-topic --ignore-stdin
  # ==============================
  # Scanner
  # ==============================
  scanner:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile
    container_name: scanner
    depends_on:
      search-node:
        condition: service_healthy
      mk-topic:
        condition: service_completed_successfully
      mk-subscription:
        condition: service_completed_successfully
    environment:
      MS_REPOSITORY_OPENSEARCH_ADDRESSES: http://search-node:9200
      PUBSUB_EMULATOR_HOST: 'pubsub:8085'
      PUBSUB_PROJECT_ID: test-project
